name: Deploy to PyPI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: "Deploy to PyPI"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get git-tags
        run: |
          git fetch --prune --unshallow --tags
          git tag --list

      - name: Retrieve version
        id: version
        run: |
          VERSION=$(cat py/visdom/VERSION)
          echo "TAG_NAME=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG_EXISTS=$(git tag | grep v$VERSION | wc -l)" >> $GITHUB_OUTPUT

      - name: Show version
        run: |
          echo "Version name: ${{ steps.version.outputs.TAG_NAME }}"
          echo "Existing Matching Tags: ${{ steps.version.outputs.TAG_EXISTS }}"

      - name: Create Release
        if: ${{ steps.version.outputs.TAG_EXISTS == '0' }}
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.TAG_NAME }}
          name: "Visdom v${{ steps.version.outputs.TAG_NAME }}"
          generate_release_notes: true

      - name: Set up Python
        if: ${{ steps.version.outputs.TAG_EXISTS == '0' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        if: ${{ steps.version.outputs.TAG_EXISTS == '0' }}
        run: |
          python -m pip install --upgrade pip
          python setup.py sdist

      - name: Publish a Python distribution to PyPI
        if: ${{ steps.version.outputs.TAG_EXISTS == '0' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
